FROM node:24-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG VITE_API_BASE_URL=""
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
RUN npm run build

FROM node:24-alpine
RUN npm i -g serve
COPY --from=build /app/dist /app/dist
EXPOSE 3000
CMD ["serve", "/app/dist", "-l", "3000"]
