CREATE TABLE notes (
   id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
   user_id UNIQUEIDENTIFIER NOT NULL,
   title NVARCHAR(255) NOT NULL,
   content NVARCHAR(MAX),
   created_at DATETIME DEFAULT GETDATE(),
   updated_at DATETIME NULL,
   FOREIGN KEY (user_id) REFERENCES users(id)
);